### ISSUE TITLE
ADM-001 Registrar Perfiles de Usuarios

### ISSUE THREAD

**Issue by Tawnny27** [Tawnny27/ProyectoFinal_Consenti2#1]
**Como administradora quiero registrar usuarios con los perfiles de directora, maestras, padres de familia y niños para que tengan una cuenta activa y puedan iniciar sesión en el sistema del centro educativo.**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Escenario | Criterio de   Aceptación | Contexto | Evento | Resultado
-- | -- | -- | -- | --
1 | El   usuario directora/maestra es registrado exitosamente  por la administradora | En   caso que la información ingresada como nombre, cedula, edad, numero   telefónico, correo, puesto, contraseña temporal sea válida y completa | Cuando   la administradora presione el botón de registro | El   sitio web creara la nueva cuenta, enviara una notificación al correo del   usuario para que proceda a cambiar la contraseña temporal, mostrara un   mensaje de que el registro se hizo exitosamente y la maestra o directora   podrá iniciar sesión en el sistema.
2 | El   usuario padre de familia es registrado exitosamente  por la administradora | En   caso que la información ingresada como nombre, cedula del padre, edad, numero   telefónico, correo, contraseña temporal sea válida y completa | Cuando   la administradora presione el botón de registro | El   sitio web creara la nueva cuenta, enviara una notificación al correo del   usuario para que proceda a cambiar la contraseña temporal, mostrara un   mensaje de que el registro se hizo exitosamente y lo redigira a la pantalla   de registró de niños que se vincularan a ese padre de familia
3 | El   registro del padre de familia se da exitosamente y la administradora puede   registrar los niños matriculados al padre | En   caso que el registro del padre se haya hecho con éxito | Cuando   la administradora presione el botón de registrar niños | El   sistema despliega un formulario por cada niño que se vaya a registrar para   que ingrese los datos del nombre, la cedula del niño, la edad, una fotografía   y un botón de registro
4 | El   registro no se realiza y muestra mensaje informativo que el usuario se   encuentra registrado | En   caso que el usuario ya este registrado en el sistema | Cuando   ingrese la información de cedula | El   sitio web evaluará si ya la cedula existe en el sistema y mostrará un mensaje   de alerta de que el usuario ya se encuentra registrado
5 | El   registro no se realiza y muestra mensaje informativo que la información   ingresada es incompleta | En   caso que la administradora no complete la información del con todos los   campos obligatorios | Cuando   la administradora presione el botón de registro | El sitio web evaluará la información   ingresada, y si encuentra incongruencias (como campos obligatorios vacíos,   formatos incorrectos), mostrará un mensaje de alerta indicando los errores   específicos que deben corregirse antes de poder continuar con el registro.

</body>

</html>

**Comment by murillo626** [comment]
Falta corregir front
